### PR TITLE
Update to Java 20

### PR DESCRIPTION
**Pull request by scordio**
JDK 20.0.1 has been released ~today~ yesterday and I've noticed some failures like [this one](https://github.com/assertj/assertj/actions/runs/4737259617/jobs/8409900027).

I've taken inspiration from #41 for a fix, I hope I covered all the needed points.

### CODE REVIEW

**Review by sormuras — APPROVED** [review]
Merci, Stefano. Changes look good to me.

**Comment by scordio** [comment]
Looks good so far 👍 https://github.com/assertj/assertj/actions/runs/4739705996/jobs/8420640816

Thanks for merging!

**Comment by sormuras** [comment]
The run you linked indicates that only the mapping file update was missing - as your workflow uses `v1` of `oracle-actions/setup-java`. That update would/should have happend automatically today/or so.

Thanks for updating the defaults and documentation - we will release a new version of this action soon, with moving the `v1` branch to that new release as well.

**Comment by scordio** [comment]
Wasn't the mapping file updated with 33f8639ae0bbc8bdaee0773d831dcb39c58e839d? Not sure I understood where the gap was.

**Comment by sormuras** [comment]
Yes, you are right. The mapping was updated; yet the parser/lister (`ListOpenJavaDevelopmentKits.java`) was out of sync. This is what your PR fixed and generated the new mapping file - which now consumable by current `@v1` and `@main` versions of this action alike.

**Pull request merged**
